### ISSUE TITLE
UseDatabaseErrorPage(IApplicationBuilder) is obsolete and will be removed in a future version

### ISSUE THREAD

**Issue by alexis-** [DuendeSoftware/IdentityServer.Templates#10]
https://github.com/DuendeSoftware/IdentityServer.Templates/blob/d0d5310bca44f27142cb6967d1663694b2705cd0/src/IdentityServerAspNetIdentity/Startup.cs#L74
https://github.com/DuendeSoftware/IdentityServer.Templates/blob/d0d5310bca44f27142cb6967d1663694b2705cd0/src/IdentityServerEntityFramework/Startup.cs#L78

FYI, the `UseDatabaseErrorPage(IApplicationBuilder)` method is marked as obsolete in the latest (non pre-release) version of Microsoft.AspNetCore (5.0.5.0).

```
Warning	CS0618	'DatabaseErrorPageExtensions.UseDatabaseErrorPage(IApplicationBuilder)' is obsolete: 'This is obsolete and will be removed in a future version. Use DatabaseDeveloperPageExceptionFilter instead, see documentation at https://aka.ms/DatabaseDeveloperPageExceptionFilter.'
```

**Comment by brockallen** [comment]
https://github.com/aspnet/Announcements/issues/432

**Comment by leastprivilege** [comment]
status?

**Comment by brockallen** [comment]
I don't think we've had that in our main repo for some time. Once the templates are updated to match, then it'll be gone.
