### ISSUE TITLE
Formatting/whitespace and analyzer issues in templates

### ISSUE THREAD

**Issue by tillig** [DuendeSoftware/IdentityServer.Templates#17]
After doing a `dotnet new isinmem` I enabled the default Roslyn analyzers on the project by adding `<AnalysisMode>All</AnalysisMode>` to the project. They catch a few low-hanging fruit sorts of fixes like [this logging line that doesn't use placeholders right](https://github.com/DuendeSoftware/IdentityServer.Templates/blob/c448c19b3096c0972463a04e30e26a18a05d3d74/src/IdentityServerInMem/Pages/Consent/Index.cshtml.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L130)...

```c#
_logger.LogError("No consent request matching request: {0}", returnUrl);
```

...and [methods with unused parameters](https://github.com/DuendeSoftware/IdentityServer.Templates/blob/c448c19b3096c0972463a04e30e26a18a05d3d74/src/IdentityServerInMem/Pages/Consent/Index.cshtml.cs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L136).

I also tried adding StyleCop analyzers and found a lot of areas with extra/trailing whitespace, etc. Again, minor sort of low-hanging fruit things.

I recognize it's not necessarily interesting to abide by all the analyzers, just some of this seems like it'd provide a slightly cleaner out-of-the-box experience for folks using the analyzers.

I'd be happy to submit a PR to fix some of these things, but I figured I'd file an issue first to see if that's something you'd be interested in before going to the work of doing the fixes. Some of this could be helped by having an `.editorconfig` in the repo, too, which I'd be happy to help with (could steal from the [main repo](https://github.com/DuendeSoftware/IdentityServer/blob/main/.editorconfig) and add, say, .csproj settings).

**Comment by brockallen** [comment]
Hi Travis --

Thanks for this. We'll turn on those analyzers and do some cleanup based on the feedback. That would be a good cleanup exercise.

Thx!

**Comment by brockallen** [comment]
I opened up a TODO over in in the main repo for this, so I'll close this issue. Thx again!
