### ISSUE TITLE
Incorrect Redirect Page for External Login Challenge

### ISSUE THREAD

**Issue by darena-pjindal** [DuendeSoftware/IdentityServer.Templates#19]
The redirect should be only to /ExternalLogin/Challenge, NOT /ExternalLogin/Challenge/Index . 

![image](https://user-images.githubusercontent.com/45796558/149915063-2c421f00-04c3-4bfb-8148-ef206da1cea6.png)

**Comment by brockallen** [comment]
Fixed -- Thank you!
