### ISSUE TITLE
Consent Page Location

### ISSUE THREAD

**Issue by darena-pjindal** [DuendeSoftware/IdentityServer.Templates#20]
Hello, 
I am testing the latest version with asp.net core Identity. I created a Razor pages application with identity as suggested in the docs. I have copied the consent and grants folders under pages. When I configure a client with "Require Consent = True", it is redirecting me to /consent. It should be identity/pages/consent. Could you please share where we can update this setting?

![image](https://user-images.githubusercontent.com/45796558/150057679-a66df610-8c1a-4947-8620-4f020d4de7fa.png)

**Comment by darena-pjindal** [comment]
I figured out that we can set the location of the consent page through  UserInteraction.ConsentUrl. Thanks.

**Comment by brockallen** [comment]
Thanks for the feedback. I'll leave this open to check if there's a bug in our templates. Thanks!

**Comment by brockallen** [comment]
Oh I see, @darena-pjindal -- you copied our quickstart pages under the ~/identity area folder in your project?

**Comment by darena-pjindal** [comment]
@brockallen  - That is correct. I started with a default Microsoft template and was adding copying files from the identity server templates to have a clean structure. 
![image](https://user-images.githubusercontent.com/45796558/150433102-9df4fc5b-ce79-4d08-ba23-7088a095f72b.png)

**Comment by brockallen** [comment]
Ah ok, so yea, in that case there's no bug per-se in our template. I did open an issue in our quickstart docs to mention this, though. Thanks!
