### ISSUE TITLE
Issues using GetExternalLoginInfoAsync() from SignInManager in External Login callback

### ISSUE THREAD

**Issue by darena-pjindal** [DuendeSoftware/IdentityServer.Templates#23]
The SignInManager for Microsoft Identity provides couple methods to get details on the external login - GetExternalLoginInfoAsync and UpdateExternalAuthenticationTokensAsync. These default identity setup assumes that the authentication properties have a key called "LoginProvider". The Challenge and Callback methods in the samples use "scheme" as a key to identify the same property. This causes the SignInManager methods to return null. If you could change that to LoginProvider, it would allow to use the signinmanager methods in the call back method and provide better integration with identity. As a workaround, I verified that I was able to access that method by adding an additional property to the challenge method. 

![image](https://user-images.githubusercontent.com/45796558/150523978-ae619cde-6097-4e46-8e6a-b1e59513c7f4.png)

**Comment by brockallen** [comment]
We just don't use `GetExternalLoginInfoAsync` in our quickstart (mainly because most of our quickstart code has to work with and without ASP.NET Identity). Feel free to do this in your own project though.
