### ISSUE TITLE
Use HTTPS Redirection and HSTS

### ISSUE THREAD

**Issue by jfoshee** [DuendeSoftware/IdentityServer.Templates#24]
It seems like the default case for an Identity Server should be to have HTTPS and HSTS (in production) by default.  In the very unusual cases where it is not desired, the code could easily be removed.

https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl

So the section of `HostingExtensions.ConfigurePipeline` becomes...

```csharp
        if (app.Environment.IsDevelopment())
        {
            app.UseDeveloperExceptionPage();
        }
        else
        {
            // Require HSTS in Production to mitigate chance of MITM on an initial http:// request
            app.UseHsts();
        }
        // Require HTTPS to avoid eavesdropping on credentials
        app.UseHttpsRedirection();
        app.UseStaticFiles();
```

**Comment by brockallen** [comment]
There's all kinds of things people may or may not want in their host. That's the sort of thing we expect the developer to know if or what they want, and we stay out of that.
