### ISSUE TITLE
Quickstart UI user menu does not open in Firefox

### ISSUE THREAD

**Issue by josephdecock** [DuendeSoftware/IdentityServer.Templates#27]
# Summary:
The quickstart UI's dropdown menu under the username with the logout link doesn't open in Firefox. 
My guess is this is a bootstrap issue. Currently we are using bootstrap 4.5.3. Update options include 4.6.1 or 5.1.3.

# Repro Steps
1. Install the quickstart ui (isui) template
2. In Firefox, Login
4. Click on the username dropdown in the header

Expected: Menu opens with logout button
Actual: nothing happens

# Version details:
Firefox version: 102.0.1 (64-bit)
Duende.IdentityServer.Templates version: 6.1.1

**Comment by leastprivilege** [comment]
Could you fix it please?

**Comment by josephdecock** [comment]
There may not be anything that needs to be done - the issue has now stopped reproducing for me. If it does come back, I’ll try upgrading bootstrap, probably all the way to the latest version (unless you’d like to avoid the upgrade from bootstrap 4 to 5. I’m not a bootstrap expert but get the impression it is not a difficult upgrade).

**Comment by brockallen** [comment]
Just tried -- can't repro.
